INSERT INTO FONDA(ID_FONDA, NOMBRE, LATITUD, LONGITUD, DIRECCION, TELEFONO, HABILITADO) 
VALUES(SEQ_ID_FONDA.NEXTVAL, 'Yenee Guendaroo', '19.4047527', '-99.1534128', 'Nicaragua 50, Colonia Buenos Aires Cuathemoc', 
'5527119309', 1);

INSERT INTO FONDA(ID_FONDA, NOMBRE, LATITUD, LONGITUD, DIRECCION, TELEFONO, HABILITADO) 
VALUES(SEQ_ID_FONDA.NEXTVAL, 'El buen Sazón', '19.4047944', '-99.1471684', 'I Barajas Lozano, Colonia Buenos Aires Cuathemoc', 
'5527119309', 1);

INSERT INTO FONDA(ID_FONDA, NOMBRE, LATITUD, LONGITUD, DIRECCION, TELEFONO, HABILITADO) 
VALUES(SEQ_ID_FONDA.NEXTVAL, 'Tiendita de Barrio', '19.4102591', '-99.1490451', '357 Dr José María Vertiz', 
'5527119309', 1);

SELECT * FROM FONDA;

----------------------------------------------------------------------------------------------------------------

INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'QUESADILLAS Y GORDITAS');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'TAMALES');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'FONDITAS');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'POLLO');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'TORTAS Y SANDWICHES');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'TACOS');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'HAMBURGUESAS, HOT.DOGS Y PIZZAS');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'ENSALADAS');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'BARBACOA');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'POZOLE');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'COMIDA ASIATICA');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'MARISCOS');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'PANCITA');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'AGUAS Y JUGOS');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'POSTRES');
INSERT INTO CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES(SEQ_ID_CATEGORIA.NEXTVAL, 'PANBAZOS');

SELECT * FROM CATEGORIA;

----------------------------------------------------------------------------------------------------------------

INSERT INTO FONDA_CATEGORIA(ID_FONDA, ID_CATEGORIA) VALUES(1, 1);
INSERT INTO FONDA_CATEGORIA(ID_FONDA, ID_CATEGORIA) VALUES(1, 3);
INSERT INTO FONDA_CATEGORIA(ID_FONDA, ID_CATEGORIA) VALUES(1, 6);
INSERT INTO FONDA_CATEGORIA(ID_FONDA, ID_CATEGORIA) VALUES(1, 9);
INSERT INTO FONDA_CATEGORIA(ID_FONDA, ID_CATEGORIA) VALUES(1, 10);
INSERT INTO FONDA_CATEGORIA(ID_FONDA, ID_CATEGORIA) VALUES(1, 13);

INSERT INTO FONDA_CATEGORIA(ID_FONDA, ID_CATEGORIA) VALUES(2, 2);
INSERT INTO FONDA_CATEGORIA(ID_FONDA, ID_CATEGORIA) VALUES(2, 4);
INSERT INTO FONDA_CATEGORIA(ID_FONDA, ID_CATEGORIA) VALUES(2, 5);
INSERT INTO FONDA_CATEGORIA(ID_FONDA, ID_CATEGORIA) VALUES(2, 8);

INSERT INTO FONDA_CATEGORIA(ID_FONDA, ID_CATEGORIA) VALUES(3, 12);
INSERT INTO FONDA_CATEGORIA(ID_FONDA, ID_CATEGORIA) VALUES(3, 14);
INSERT INTO FONDA_CATEGORIA(ID_FONDA, ID_CATEGORIA) VALUES(3, 15);

SELECT * FROM FONDA_CATEGORIA;
SELECT * FROM CATEGORIA;

----------------------------------------------------------------------------------------------------------------

INSERT INTO DIA_SEMANA(ID_DIA, DESCRIPCION) VALUES(SEQ_ID_DIA.NEXTVAL, 'LUNES');
INSERT INTO DIA_SEMANA(ID_DIA, DESCRIPCION) VALUES(SEQ_ID_DIA.NEXTVAL, 'MARTES');
INSERT INTO DIA_SEMANA(ID_DIA, DESCRIPCION) VALUES(SEQ_ID_DIA.NEXTVAL, 'MIERCOLES');
INSERT INTO DIA_SEMANA(ID_DIA, DESCRIPCION) VALUES(SEQ_ID_DIA.NEXTVAL, 'JUEVES');
INSERT INTO DIA_SEMANA(ID_DIA, DESCRIPCION) VALUES(SEQ_ID_DIA.NEXTVAL, 'VIERNES');
INSERT INTO DIA_SEMANA(ID_DIA, DESCRIPCION) VALUES(SEQ_ID_DIA.NEXTVAL, 'SABADO');
INSERT INTO DIA_SEMANA(ID_DIA, DESCRIPCION) VALUES(SEQ_ID_DIA.NEXTVAL, 'DOMINGO');

SELECT * FROM DIA_SEMANA;

----------------------------------------------------------------------------------------------------------------

INSERT INTO SUSCRIPCION(ID_FONDA, FECHA_PAGO, FECHA_TERMINO, AL_CORRIENTE) VALUES(1, '12-FEB-16', '12-FEB-17', 1);

SELECT * FROM SUSCRIPCION;

----------------------------------------------------------------------------------------------------------------

INSERT INTO HORARIO_SERVICIO(ID_HORARIO, ID_FONDA, ID_DIA, HORARIO_APERTURA, HORARIO_CIERRE) 
VALUES(SEQ_ID_HORARIO.NEXTVAL, 1, 1, '09:00', '16:00');

INSERT INTO HORARIO_SERVICIO(ID_HORARIO, ID_FONDA, ID_DIA, HORARIO_APERTURA, HORARIO_CIERRE) 
VALUES(SEQ_ID_HORARIO.NEXTVAL, 1, 2, '09:00', '16:00');

INSERT INTO HORARIO_SERVICIO(ID_HORARIO, ID_FONDA, ID_DIA, HORARIO_APERTURA, HORARIO_CIERRE) 
VALUES(SEQ_ID_HORARIO.NEXTVAL, 1, 3, '09:00', '16:00');

INSERT INTO HORARIO_SERVICIO(ID_HORARIO, ID_FONDA, ID_DIA, HORARIO_APERTURA, HORARIO_CIERRE) 
VALUES(SEQ_ID_HORARIO.NEXTVAL, 1, 4, '09:00', '16:00');

INSERT INTO HORARIO_SERVICIO(ID_HORARIO, ID_FONDA, ID_DIA, HORARIO_APERTURA, HORARIO_CIERRE) 
VALUES(SEQ_ID_HORARIO.NEXTVAL, 1, 5, '09:00', '16:00');

INSERT INTO HORARIO_SERVICIO(ID_HORARIO, ID_FONDA, ID_DIA, HORARIO_APERTURA, HORARIO_CIERRE) 
VALUES(SEQ_ID_HORARIO.NEXTVAL, 1, 6, '09:00', '16:00');

INSERT INTO HORARIO_SERVICIO(ID_HORARIO, ID_FONDA, ID_DIA, HORARIO_APERTURA, HORARIO_CIERRE) 
VALUES(SEQ_ID_HORARIO.NEXTVAL, 1, 6, '18:00', '23:00');

SELECT * FROM HORARIO_SERVICIO;

----------------------------------------------------------------------------------------------------------------

INSERT INTO USUARIO(ID_USUARIO, NOMBRE, USUARIO, CONTRASENA) 
VALUES(SEQ_ID_USUARIO.NEXTVAL, 'Felipe Contreras Carrillo', 'pepe', 'example1234');

SELECT * FROM USUARIO;

----------------------------------------------------------------------------------------------------------------

INSERT INTO FONDA_FAVORITO(ID_FONDA, ID_USUARIO) VALUES(1, 1);
INSERT INTO FONDA_FAVORITO(ID_FONDA, ID_USUARIO) VALUES(2, 1);
INSERT INTO FONDA_FAVORITO(ID_FONDA, ID_USUARIO) VALUES(3, 1);

SELECT * FROM FONDA_FAVORITO;

----------------------------------------------------------------------------------------------------------------

SELECT ID_HORARIO, ID_FONDA, HORARIO_APERTURA, HORARIO_CIERRE
FROM HORARIO_SERVICIO H;



