
package com.mx.udev.godinez.web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.mx.udev.godinez.web.types.CalculateDistanceRequest;
import com.mx.udev.godinez.web.types.CalculateDistanceResponse;
import com.mx.udev.godinez.web.types.GetAllCategoriesRequest;
import com.mx.udev.godinez.web.types.GetAllCategoriesResponse;
import com.mx.udev.godinez.web.types.GetNearbyPlacesRequest;
import com.mx.udev.godinez.web.types.GetNearbyPlacesResponse;
import com.mx.udev.godinez.web.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GodinezLunchPort", targetNamespace = "http://www.xmlns.udev.com/GodinezLunch/GL/wsdl/1.0/GodinezLunchWS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GodinezLunchWS {


    /**
     * 
     * @param calculateDistanceRequest
     * @return
     *     returns com.mx.udev.godinez.web.types.CalculateDistanceResponse
     */
    @WebMethod(action = "http://www.udev.com/GodinezLunchWS/calculateDistance")
    @WebResult(name = "calculateDistanceResponse", targetNamespace = "http://www.xmlns.udev.com/GodinezLunch/GL/datatypes/1.0", partName = "calculateDistanceResponse")
    public CalculateDistanceResponse calculateDistance(
        @WebParam(name = "calculateDistanceRequest", targetNamespace = "http://www.xmlns.udev.com/GodinezLunch/GL/datatypes/1.0", partName = "calculateDistanceRequest")
        CalculateDistanceRequest calculateDistanceRequest);

    /**
     * 
     * @param getNearbyPlacesRequest
     * @return
     *     returns com.mx.udev.godinez.web.types.GetNearbyPlacesResponse
     */
    @WebMethod(action = "http://www.udev.com/GodinezLunchWS/getNearbyPlaces")
    @WebResult(name = "getNearbyPlacesResponse", targetNamespace = "http://www.xmlns.udev.com/GodinezLunch/GL/datatypes/1.0", partName = "getNearbyPlacesResponse")
    public GetNearbyPlacesResponse getNearbyPlaces(
        @WebParam(name = "getNearbyPlacesRequest", targetNamespace = "http://www.xmlns.udev.com/GodinezLunch/GL/datatypes/1.0", partName = "getNearbyPlacesRequest")
        GetNearbyPlacesRequest getNearbyPlacesRequest);

    /**
     * 
     * @param getAllCategoriesRequest
     * @return
     *     returns com.mx.udev.godinez.web.types.GetAllCategoriesResponse
     */
    @WebMethod(action = "http://www.udev.com/GodinezLunchWS/getAllCategories")
    @WebResult(name = "getAllCategoriesResponse", targetNamespace = "http://www.xmlns.udev.com/GodinezLunch/GL/datatypes/1.0", partName = "getAllCategoriesResponse")
    public GetAllCategoriesResponse getAllCategories(
        @WebParam(name = "getAllCategoriesRequest", targetNamespace = "http://www.xmlns.udev.com/GodinezLunch/GL/datatypes/1.0", partName = "getAllCategoriesRequest")
        GetAllCategoriesRequest getAllCategoriesRequest);

}
