
package com.mx.udev.godinez.web;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GodinezLunchWSImplService", targetNamespace = "http://www.xmlns.udev.com/GodinezLunch/GL/wsdl/1.0/GodinezLunchWS", wsdlLocation = "file:/C:/Users/ocastellanos/git/godinez-lunch-app/code/godinez/godinez-web/src/main/resources/wsdl/GodinezLunchWSSOAP.wsdl")
public class GodinezLunchWSClient
    extends Service
{

    private final static URL GODINEZLUNCHWSIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.mx.udev.godinez.web.GodinezLunchWSClient.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.mx.udev.godinez.web.GodinezLunchWSClient.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/ocastellanos/git/godinez-lunch-app/code/godinez/godinez-web/src/main/resources/wsdl/GodinezLunchWSSOAP.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/ocastellanos/git/godinez-lunch-app/code/godinez/godinez-web/src/main/resources/wsdl/GodinezLunchWSSOAP.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GODINEZLUNCHWSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public GodinezLunchWSClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GodinezLunchWSClient() {
        super(GODINEZLUNCHWSIMPLSERVICE_WSDL_LOCATION, new QName("http://www.xmlns.udev.com/GodinezLunch/GL/wsdl/1.0/GodinezLunchWS", "GodinezLunchWSImplService"));
    }

    /**
     * 
     * @return
     *     returns GodinezLunchWS
     */
    @WebEndpoint(name = "GodinezLunchWSImplPort")
    public GodinezLunchWS getGodinezLunchWSImplPort() {
        return super.getPort(new QName("http://www.xmlns.udev.com/GodinezLunch/GL/wsdl/1.0/GodinezLunchWS", "GodinezLunchWSImplPort"), GodinezLunchWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GodinezLunchWS
     */
    @WebEndpoint(name = "GodinezLunchWSImplPort")
    public GodinezLunchWS getGodinezLunchWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.xmlns.udev.com/GodinezLunch/GL/wsdl/1.0/GodinezLunchWS", "GodinezLunchWSImplPort"), GodinezLunchWS.class, features);
    }

}
